### PR TITLE
Update mainnet.json

### PR DESCRIPTION
**Pull request by Exnav29**
Added node at 40.121.197.76

### CODE REVIEW

**Comment by ffox77** [comment]
@Exnav29 - This PR has merge conflicts that need to be resolved.

**Comment by Exnav29** [comment]
Updated the file.  Should I submit a new Pull Request?

**Comment by ffox77** [comment]
@Exnav29 - there is still a conflict. you can keep the same PR. commit to your same branch *bridge_add*

**Comment by ffox77** [comment]
I'm going to close this PR. The file changed in the PR has since been deleted. Please, open another PR with your changes. Follow the updated readme on how to edit the end points.

**Pull request closed without merging**
